class Data:
    MAIN_URL = 'https://qa-scooter.praktikum-services.ru/'
    ZEN_ULR = 'https://dzen.ru/?yredirect=true'
    ORDER_URL = 'https://qa-scooter.praktikum-services.ru/order'
    TEST_USER_NAME = 'Брюс'
    TEST_USER_SURNAME = 'Всемогущий'
    TEST_RENT_DATE = '29.02.2024'
    TEST_ADDRESS = 'Косой переулок, дом 1'
    TEST_METRO_STATION_NAME_BEGIN = 'ряд'
    TEST_PHONE = '+79999999999'
    RENT_COMMENT = 'Если нет чёрного жемчуга, серая безысходность тоже подойдет'
